// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcv6Iih0oIxwxU1Va0NfVRqgib4mB4pz8',
    appId: '1:1065349185714:web:e1064510730e96299309ab',
    messagingSenderId: '1065349185714',
    projectId: 'happypaws-ab9c0',
    authDomain: 'happypaws-ab9c0.firebaseapp.com',
    storageBucket: 'happypaws-ab9c0.appspot.com',
    measurementId: 'G-HWCGCNKRJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHb13IX03v9vAjUgyh00MgvEYn0Yi8BlU',
    appId: '1:1065349185714:android:7722003aff6c97c89309ab',
    messagingSenderId: '1065349185714',
    projectId: 'happypaws-ab9c0',
    storageBucket: 'happypaws-ab9c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBanwfjERWP1KdqT61P_X4l4eDlM0EdCDA',
    appId: '1:1065349185714:ios:62ba7832a077e7479309ab',
    messagingSenderId: '1065349185714',
    projectId: 'happypaws-ab9c0',
    storageBucket: 'happypaws-ab9c0.appspot.com',
    iosClientId: '1065349185714-n278e76ug8dl06eqh8k1q1tkn2a3m3g6.apps.googleusercontent.com',
    iosBundleId: 'com.example.petapp2',
  );
}
